# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               QuizDroid
tagline:             'Quiz Bowl Content and Resources'
description:         'Download <a href="https://play.google.com/store/apps/details?id=io.github.arjunpanickssery.quizdroid&hl=en_US">QuizDroid</a> for your Android device.'
url:                 http://quizdroid.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Arjun Panickssery
  url:               https://quizdroid.github.io
  email:             quizdroid.contact@gmail.com

# Custom vars
version:             1.0.0
